packer {
  required_plugins {
    xenserver = {
      version = " >= v0.7.0 "
      source  = "github.com/ddelnano/xenserver"
    }
  }
}

variable "remote_host" {
  type        = string
  description = "The IP or FQDN of your XCP-ng. It must be the master"
  sensitive   = true
  default     = "192.168.5.27"
}

variable "remote_username" {
  type        = string
  description = "The username used to interact with your XCP-ng"
  sensitive   = true
  default     = "root"
}

variable "remote_password" {
  type        = string
  description = "The password used to interact with your XCP-ng"
  sensitive   = true
  default     = "Trin121201"
}

variable "sr_iso_name" {
  type        = string
  description = "The ISO-SR packer will use"
  default     = "ISO"
}

variable "sr_name" {
  type        = string
  description = "The name of the SR packer will use"
  default     = "XENX Storage"
}

source "xenserver-iso" "windows_server" {
  iso_url        = "http://yourserver/path/to/windows_server.iso"
  iso_checksum   = "sha256:your_iso_checksum_here"

  sr_iso_name    = var.sr_iso_name
  sr_name        = var.sr_name
  tools_iso_name = ""

  remote_host     = var.remote_host
  remote_password = var.remote_password
  remote_username = var.remote_username

  http_directory = "http"
  ip_getter      = "tools"

  boot_command = [
    "<wait><wait><wait><esc><wait><wait><wait>",
    "setup.exe /unattend:http://{{.HTTPIP}}:{{.HTTPPort}}/autounattend.xml <enter>"
  ]

  clone_template   = "Windows Server"
  vm_name          = "Windows Server Template"
  vm_description   = "Windows Server template created with Packer"
  vcpus_max        = 4
  vcpus_atstartup  = 2
  vm_memory        = 4096 # MB
  disk_size        = 40960 # MB
  disk_name        = "windows disk"
  vm_tags          = ["Generated by Packer"]

  ssh_username           = "Administrator"
  ssh_password           = "YourSecurePassword"
  ssh_wait_timeout       = "60000s"
  ssh_handshake_attempts = 10000

  output_directory = "packer-windows-server"
  keep_vm          = "never"
  format           = "xva_compressed"
}

build {
  sources = ["xenserver-iso.windows_server"]
}
