- name: Generate SSH key pair
  hosts: localhost
  tasks:
    - name: Check if devuser SSH key already exists
      stat:
        path: "~/.ssh/id_rsa_devuser.pub"
      register: ssh_key_devuser

    - name: Generate devuser SSH key pair if it does not exist
      command: ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa_devuser -N ""
      when: not ssh_key_devuser.stat.exists

    - name: Check if deployment SSH key already exists
      stat:
        path: "~/.ssh/id_rsa_deploykey.pub"
      register: ssh_key_deploykey

    - name: Generate deployment SSH key pair if it does not exist
      command: ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa_deploykey -N ""
      when: not ssh_key_deploykey.stat.exists


    - name: Ensure the .ssh directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    - name: Read the devuser SSH public key
      slurp:
        src: ~/.ssh/id_rsa_devuser.pub
      register: ssh_pub_key_devuser

    - name: Read the deployment SSH public key
      slurp:
        src: ~/.ssh/id_rsa_deploykey.pub
      register: ssh_pub_key_deploykey

    - name: Save the SSH public key to a variable
      set_fact:
        ssh_devuser_public_key: "{{ ssh_pub_key_devuser.content | b64decode }}"
        ssh_deploy_public_key: "{{ ssh_pub_key_deploykey.content | b64decode }}"
