- name: Ensure log rotation is configured
  copy:
    dest: /etc/logrotate.d/custom_logs
    content: |
      /var/log/*.log {
          weekly
          rotate 4
          compress
          missingok
          notifempty
      }
